---
- hosts: ansible-server
  become: false
  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/kubernetes 

  - name: create tag to image
    command: docker tag simple-devops-image renegmedal/simple-devops-image
 
  - name: push image on to dockerhub
    command: docker push renegmedal/simple-devops-image:latest
 
  - name: remove docker images from ansible server
    command: docker rmi simple-devops-image:latest renegmedal/simple-devops-image 
    ignore_errors: yes
